- .github/workflows/cont_integration.yml
Added caching to `.github/workflows/cont_integration.yml` which speeds up the build from ~15 mins to ~30 seconds by reading electrs (and bitcoind) from cache. 
I think if we do the same sort of caching we can incorporate this into our `bdk` CI instead of using docker.
> Add cache to workflow

- Readme.md
- src/lib.rs
Same as https://github.com/RCasatta/bitcoind/pull/7.
With this branch I was able to use ElectrsD with elementsd and electrs compiled with `--features liquid`.
If this is merged we can add this crate as dev dependency to GDK.
> Add ElectrsD::with_conf

- Cargo.toml
- build.rs
- src/lib.rs
Same rationale as https://github.com/RCasatta/bitcoind/pull/18
[edit] it looks like that one will have to be fixed before I can get CI to pass here
> Use OUT_DIR when building

- src/lib.rs
Making the crate's Error type `std::Error` helps in propagating them easier in downstream application.
Example
```
fn some_func(bitcoind: &electrsd::bitcoind::Bitcoind) -> Result<(), Box<dyn std::error::Error>> {
... do something
let bitcoind = electrsd::bitcoind::BitcoinD::with_conf(bitcoind_exe, &bitcoind_conf)?;
OK(())
}
```
This will the work.
Depends on https://github.com/RCasatta/bitcoind/pull/44
> Implement std::error::Error for crate::Error

- .github/workflows/cont_integration.yml
- Cargo.toml
- src/lib.rs
Fixes #35 
Replay the same changes of https://github.com/RCasatta/bitcoind/pull/52 for `electrs` index directory.
I couldn't figure a good way to stop the `electrs` server. So right now the `drop` is same as before. I am not entirely sure if that's total safe.. Looking or suggestions..
> Add configurable workdir options

- Cargo.toml
include 0.23 bitcoind features
use electrum client 0.10 to avoid depending on bitcoin 0.27
> bump to 0.19.1

- Cargo.toml
This is the last release of electrum-client before bumping rust-bitcoin to 0.29
It includes the recent fixes and some API improvements that I wanted to make available to projects using 0.28 (like bdk).
> Update electrum-client to 0.11

- Cargo.toml
- src/lib.rs
bumps bitcoind, electrum-client and nix deps
> bump version to 0.21, bump deps (bitcoin 0.29)

- src/lib.rs
Without the reexport, downstream users have to additionally declare the `electrum_client` crate in their `Cargo.toml` if they want to be able to use the methods defined by the `ElectrumApi` trait.
> Re-export `electrum_client`

- src/lib.rs
otherwise providing an old version of electrs via ELECTRS_EXEC doesn't work
> use also legacy feature to discriminate older version

- Cargo.toml
- build.rs
Multiple projects in the `rust-bitcoin` space are currently planning a migration away from `ureq` to `minreq`, as it provides better MSRV guarantees.
In this PR we trivially replace the `ureq` dependency by `minreq`. Note that this doesn't necessarily lower the MSRV right away due to the included `rustls` dependency, but is a preparatory step.
Also see https://github.com/RCasatta/bitcoind/pull/110.
> Replace `ureq` with `minreq`

- README.md
- build.rs
Equivalent to https://github.com/RCasatta/bitcoind/pull/107, this PR makes the endpoint configurable from which we download the binaries.
> Make download endpoint configurable

- .github/workflows/cont_integration.yml
- Cargo.toml
- README.md
- build.rs
- src/error.rs
- src/lib.rs
- bump version to `0.26.0`
- normalize ENV vars as the same prefix `bitcoind`: `ELECTRS_EXE` -> `ELECTRS_EXEC`
- optionally download when building to allow Nix builds
- fix missnamed feature in `README.md`: `bitcoind_23_0` -> `bitcoind_23_1`
- introduces `which` to find executables
- introduces CI to test without auto-download features
This makes a Nix CI pass, check: https://github.com/realeinherjar/bdk/actions/runs/6512925971/job/17691535222 (ignore the failed ones, MSRV, I am still working on those)
- Closes #68
> feat: optional download

- Cargo.toml
- src/ext.rs
- src/versions.rs
Otherwise an errors is thrown during an NDK build which should in theory not need dev-dependcies but it does
> define OS as undefined when neither linux nor macos

- Cargo.toml
- README.md
- build.rs
- src/lib.rs
Similar to https://github.com/rust-bitcoin/bitcoind/pull/154
Context: https://github.com/Blockstream/electrs/pull/73
> Skip download

- Cargo.toml
The `electrum-client` crate released v0.21 recently. It would be great to upgrade and get a release out to enable compatibility of `ElectrumApi` for crates that already upgraded (such as LDK). 
(cc @RCasatta)
> Upgrade to `electrum-client` v0.21

- .github/workflows/build_electrs.yml
This is to build electrs v0.10.6, which is the most recent tag.
I was able to run this updated workflow here: https://github.com/jp1ac4/electrsd/actions/runs/11542187543.
I can add a corresponding electrs_0_10_6 feature too if you like.
> Build electrs 0.10.6

- .github/workflows/build_electrs.yml
- .github/workflows/cont_integration.yml
- Cargo.toml
- README.md
- src/error.rs
- src/ext.rs
- src/lib.rs
https://github.com/RCasatta/electrsd/issues/88
> change bitcoind -> corepc_node

- Cargo.toml
We bump to the newest version of `electrum-client` (v0.22), which was released recently.
It would be great to upgrade and get a release out to enable compatibility of `ElectrumApi` for crates that already upgraded (such as LDK).
> Upgrade to `electrum-client` v0.22

- src/lib.rs
When upgrading to `corepc_node`, the re-export of `bitcoind` was replaced with a re-export of `corepc-client`. While the latter can still be useful, still exporting the whole `corepc_node` might be good to allow users accessing exactly the `corepc_node` version referenced by `electrsd`.
> Re-export `corepc_node`

- Cargo.toml
Version `0.6` was just released, here we bump the version to allow downstream users to make use of the newly introduced features.
> Bump `corepc-node`/`corepc-client` to the latest v0.6

- .github/workflows/cont_integration.yml
Don't bother doing all of them just do the lastest 5 excluding 28_0 because it doesn't work here right now - needs further debugging.
Also do 0_17_1 because its the default now in `corepc-node` so running `cargo build` in this crate implicitly uses that feature.
Fix: #97
> CI: Add a job to test a few versions of the corepc crates

- Cargo.toml
.. which were just released and features some bugfixes we require to run it in our CI.
> Bump `corepc` crates to 0.7

- Cargo.toml
We bump the `electrum-client` dependency to the recently-introduced version v0.24.0.
@RCasatta As we'll need this to unbreak our CI after bumping the client version ourselves, it would be great if `electrsd` could cut a release for this!
> Bump `electrum-client` to v0.24.0
